database:
  type: sqlite

  prefix: anniv2_

  local:
    path: anni.db

default-arena:
  enabled-teams:
    red: true
    blue: true
    green: true
    yellow: true

  team-min-players: 2
  team-max-players: 30
  default-health: 100

on-votifier:
  enabled: true

  points: 1000

kits:
  enable-custom-kit: true
  custom-kit-only: false